#!/bin/bash

usage() {
    cat <<EOF
- Handle hyprland events

Usage: hyprevents -f|--file <event_handler> [options...]

Options:
  -h, --help        show help message
  -k, --kill        kill already started event handler
  -r, --reload      realod already started event handler
EOF
}

EVENT_LOADER="$(dirname "$0")/event_loader"

argparse() {
    local args=$(getopt -a -n hyprevents \
                        -o hf:kr \
                        --long help,file:,kill,reload -- "$@")

    [[ $? != 0 ]] && usage && exit
    eval set -- "$args"

    KILL=0
    RELOAD=0
    while :; do
        case "$1" in
            -h | --help)
                usage;
                exit ;;
            -f | --file)
                shift;
                EVENT_FILE=$1
                ;;
            -k | --kill)
                KILL=1
                ;;
            -r | --reload)
                RELOAD=1
                ;;
            --)
                shift;
                break ;;
            *)
                echo "Unexpected option: $1";
                usage;
                exit ;;
        esac
        shift
    done
}

argparse "$0" "$@"

[ -z "$EVENT_FILE" ] && echo "Event handler not provided." && usage && exit
[ $KILL == 1 ] && pkill -f "$EVENT_LOADER $EVENT_FILE" && exit
[ $RELOAD == 1 ] && pkill -USR1 -f "$EVENT_LOADER $EVENT_FILE" && exit

socat -u UNIX-CONNECT:"/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock" \
         EXEC:"$EVENT_LOADER $EVENT_FILE",nofork
